"""added categories to garagesale model and schema

Revision ID: 10aa1b9f886e
Revises: 516a0941ce82
Create Date: 2023-06-13 10:17:56.609474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aa1b9f886e'
down_revision = '516a0941ce82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_sale', schema=None) as batch_op:
        batch_op.drop_column('categories')

    # ### end Alembic commands ###
