"""removed categories from garagesale

Revision ID: 3f33b4115a63
Revises: 10aa1b9f886e
Create Date: 2023-06-15 15:44:44.406695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f33b4115a63'
down_revision = '10aa1b9f886e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_sale', schema=None) as batch_op:
        batch_op.drop_column('categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
