"""added name to the garage sale model

Revision ID: 516a0941ce82
Revises: 3d06bac87bae
Create Date: 2023-06-13 10:04:49.189046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516a0941ce82'
down_revision = '3d06bac87bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garage_sale', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
